--- 
pid: tmp/pids/thin.pid
adapter: rails
log: log/thin.log
timeout: 30
max_conns: 1024
port: 3100
environment: production
max_persistent_conns: 512
servers: 1
daemonize: true
require: []

threaded: true
address: 0.0.0.0
